oss:
  endpoint:
    oss-cn-beijing.aliyuncs.com
  bucket:
    ossbucket000

OSS_ACCESS_KEY_ID:
  LTAI5t6HL3hwNEZWrk1k668E

OSS_ACCESS_KEY_SECRET:
  CwbQ3RJiNYFtdYGkLQ9RwenCbXJVmw
cache:
  expiration: 300